import '../models/kit_gap.dart';

/// Builds the markdown content for Kit Gap PR files.
class GitHubPrBuilder {
  static String branchName(List<KitGap> gaps) {
    final slug = gaps.first.suggestedComponentName
            ?.toLowerCase()
            .replaceAll(RegExp(r'[^a-z0-9]+'), '-') ??
        'component';
    final date = DateTime.now().toIso8601String().substring(0, 10);
    return 'kit-gap/$date-$slug';
  }

  static String prTitle(List<KitGap> gaps) {
    if (gaps.length == 1) {
      return 'Kit Gap: ${gaps.first.suggestedComponentName ?? gaps.first.widgetName}';
    }
    return 'Kit Gap: ${gaps.length} new components proposed';
  }

  static String prBody(List<KitGap> gaps) {
    final buf = StringBuffer()
      ..writeln('## Kit Gap Proposal\n')
      ..writeln(
          '> Auto-generated by **Kit-Gen AI** — review, approve or close.\n');

    for (final g in gaps) {
      final priority = g.priority != null ? ' (priority: ${g.priority})' : '';
      buf
        ..writeln('### ${g.suggestedComponentName ?? g.widgetName}$priority\n')
        ..writeln('**Missing widget:** `${g.widgetName}`')
        ..writeln('**Description:** ${g.description}');
      if (g.reason != null) buf.writeln('**Reason:** ${g.reason}');
      buf.writeln();
    }

    buf
      ..writeln('---')
      ..writeln('## Checklist\n')
      ..writeln('- [ ] Reviewed proposed implementation')
      ..writeln('- [ ] Matches Tagaddod design system')
      ..writeln('- [ ] Added to `lib/tagaddod_ui_kit.dart` barrel file')
      ..writeln('- [ ] `kit-gen-dart/lib/data/components.json` updated')
      ..writeln('- [ ] Tests added');

    return buf.toString();
  }

  static String gapMarkdown(KitGap gap) {
    final buf = StringBuffer()
      ..writeln('# ${gap.suggestedComponentName ?? gap.widgetName}\n')
      ..writeln('**Status:** proposed\n')
      ..writeln('## Description\n${gap.description}\n');
    if (gap.reason != null) buf.writeln('## Reason\n${gap.reason}\n');
    if (gap.priority != null) buf.writeln('**Priority:** ${gap.priority}\n');
    if (gap.proposedImplementation != null) {
      buf
        ..writeln('## Proposed Implementation\n')
        ..writeln('```dart')
        ..writeln(gap.proposedImplementation)
        ..writeln('```');
    }
    return buf.toString();
  }

  static String toSnakeCase(String name) =>
      name.replaceAllMapped(RegExp(r'([A-Z])'), (m) => '_${m[1]!.toLowerCase()}')
          .replaceFirst(RegExp(r'^_'), '');
}
