import 'dart:io';
import 'package:args/args.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:kit_gen/services/gemini_service.dart';
import 'output_handler.dart';

Future<void> runArchGeneration(
  Logger logger,
  GeminiService gemini,
  String systemPrompt,
  String requirement,
  ArgResults results, {
  required bool verbose,
  required bool shouldRetry,
}) async {
  final progress =
      logger.progress('Generating clean architecture files');

  try {
    var result =
        await gemini.generateArchCode(requirement, systemPrompt);

    if (shouldRetry && result.files.isEmpty) {
      progress.update('Retrying with strict prompt...');
      result = await gemini.generateArchCode(
        '$requirement\n\nIMPORTANT: Follow constructor rules.',
        systemPrompt,
      );
    }

    progress.complete('Architecture generated!');

    if (verbose) {
      logger.info(darkGray.wrap('─── RAW RESPONSE ───'));
      logger.info(result.rawResponse);
      logger.info(darkGray.wrap('─── END RAW ───'));
      logger.info(
          '📊 ${result.inputTokens} in / '
          '${result.outputTokens} out '
          '(~\$${result.estimatedCost.toStringAsFixed(4)})');
    }

    final outputDir = results['output'] as String?;
    if (outputDir == null) {
      for (final f in result.files) {
        logger.info(lightGreen.wrap('── ${f.path} ──'));
        logger.info(f.code);
      }
      logger.detail('💡 Tip: -o <dir> to save files');
      return;
    }

    for (final f in result.files) {
      final file = File('$outputDir/${f.path}');
      await file.parent.create(recursive: true);
      await file.writeAsString(
          '// Generated by kit-gen\n'
          '// Requirement: $requirement\n\n'
          '${f.code}');
      logger.success('✓ Saved: ${file.path}');
    }

    if (result.hasGaps) {
      printGaps(logger, result.kitGapsList);
    }

    runValidation(logger, results);
  } catch (e) {
    progress.fail('Generation failed');
    logger.err('Error: $e');
    exit(1);
  }
}
