import 'dart:io';
import 'package:args/args.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:kit_gen/services/gemini_service.dart';

void printVerbose(
    Logger logger, GenerationResult result, bool verbose) {
  if (!verbose) return;
  logger.info(darkGray.wrap('─── RAW RESPONSE ───'));
  logger.info(result.rawResponse);
  logger.info(darkGray.wrap('─── END RAW ───'));
  logger.info(
      '📊 ${result.inputTokens} in / ${result.outputTokens} out'
      ' (~\$${result.estimatedCost.toStringAsFixed(4)})');
}

void printResult(Logger logger, GenerationResult result) {
  logger.info('');
  logger.info(lightGreen.wrap('✓ Generated Screen Code:'));
  logger.info('');
  logger.info(darkGray.wrap('─' * 80));
  logger.info(result.screenCode);
  logger.info(darkGray.wrap('─' * 80));

  if (result.hasGaps) {
    printGaps(logger, result.kitGapsList);
  } else {
    logger.info('');
    logger.success('✓ No kit gaps — all components exist!');
  }

  logger.detail(
      '📊 ${result.inputTokens} in, ${result.outputTokens} out '
      '(~\$${result.estimatedCost.toStringAsFixed(4)})');
}

void printGaps(Logger logger, List<KitGap> gaps) {
  logger.info('');
  logger.warn('⚠ Kit Gaps (${gaps.length}):');
  for (final gap in gaps) {
    logger.warn('  • ${gap.widgetName}');
    logger.detail('    ${gap.description}');
  }
  logger.warn('💡 Add these to the UI kit.');
}

void saveOutput(Logger logger, ArgResults results,
    GenerationResult result, String requirement) {
  if (results['output'] == null) {
    logger.detail('💡 Use -o <file> to save output');
    return;
  }
  final path = results['output'] as String;
  final file = File(path)..parent.createSync(recursive: true);
  final buf = StringBuffer()
    ..writeln('// Generated by kit-gen')
    ..writeln('// Requirement: $requirement')
    ..writeln('')
    ..write(result.screenCode);
  if (result.hasGaps) {
    buf.writeln('\n\n/*\n=== KIT GAPS ===');
    buf.writeln(result.kitGapsText);
    buf.writeln('*/');
  }
  file.writeAsStringSync(buf.toString());
  logger.success('✓ Saved to: $path');
}

void runValidation(Logger logger, ArgResults results) {
  if (!(results['validate'] as bool)) return;
  final path = results['output'] as String?;
  if (path == null) {
    logger.warn('--validate requires -o <file>');
    return;
  }
  final progress = logger.progress('Running dart analyze');
  final r = Process.runSync(
      'dart', ['analyze', '--fatal-infos', path]);
  if (r.exitCode == 0) {
    progress.complete('No analysis issues');
  } else {
    progress.fail('Analysis issues found');
    logger.info(r.stdout.toString());
    logger.err(r.stderr.toString());
  }
}
